#Date: 11th September 2026
#TOpics Covered: Variables and Print Statements

"""VARIABLES & PRINT STATEMENTS

1. CREATE THREE VARIABLES NAME, AGE, AND CITY AND PRINT THEIR VALUES.
2. STORE YOUR FIRST NAME AND LAST NAME IN TWO VARIABLES AND PRINT THEM TOGETHER.
3. CREATE VARIABLES FOR COLLEGE, COURSE, AND YEAR AND DISPLAY THEM IN SEPARATE LINES.
4. STORE THE VALUES 100, 25.5, "PYTHON", AND TRUE IN VARIABLES AND PRINT THEM.
5. SWAP THE VALUES OF TWO VARIABLES WITHOUT USING A THIRD VARIABLE.
6. CREATE A VARIABLE SALARY = 25000 AND PRINT: MY SALARY IS 25000.
7. CREATE VARIABLES FOR TWO NUMBERS AND PRINT THEIR SUM.
8. CREATE A VARIABLE AND PRINT ITS VALUE 5 TIMES. """

# 1. CREATE THREE VARIABLES NAME, AGE, AND CITY AND PRINT THEIR VALUES

name = "Avinash"
age = 25
city = "Chennai"
print(name)
print(age)
print(city)


# 2. STORE YOUR FIRST NAME AND LAST NAME IN TWO VARIABLES AND PRINT THEM TOGETHER

first_name = "Avinash"
last_name = "M"
print(first_name + " " + last_name)


# 3. CREATE VARIABLES FOR COLLEGE, COURSE, AND YEAR AND DISPLAY THEM IN SEPARATE LINES

college = "ABC College"
course = "B.Tech"
year = 2024
print(college)
print(course)
print(year)


# 4. STORE THE VALUES 100, 25.5, "PYTHON", AND TRUE IN VARIABLES AND PRINT THEM

a = 100
b = 25.5
c = "Python"
d = True
print(a)
print(b)
print(c)
print(d)


# 5. SWAP THE VALUES OF TWO VARIABLES WITHOUT USING A THIRD VARIABLE

x = 10
y = 20
x, y = y, x
print(x)
print(y)


# 6. CREATE A VARIABLE SALARY = 25000 AND PRINT: MY SALARY IS 25000

salary = 25000
print("My salary is", salary)


# 7. CREATE VARIABLES FOR TWO NUMBERS AND PRINT THEIR SUM

num1 = 15
num2 = 25
print(num1 + num2)


# 8. CREATE A VARIABLE AND PRINT ITS VALUE 5 TIMES

message = "Hello"
for i in range(5):
    print(message)
